/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datamanagerbuku.ui;

import datamanagerbuku.controller.BukuDataSource;
import datamanagerbuku.models.Buku;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author nicoe
 */
public class FormBukuActivity extends javax.swing.JFrame {
    
    private Buku buku;

    private void showError(String message){
        JOptionPane.showMessageDialog(this, message,"Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void showSucceed(String message){
        JOptionPane.showMessageDialog(this, message,"Sukses", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void showOldDataof(Buku buku){
        judulField.setText(buku.getJudulBuku());
        pengarangField.setText(buku.getPengarang());
        
        String penerbit =buku.getPenerbit();
        switch (penerbit){
            case "Yudhistira" : yudhistiraRb.setSelected(true);break;
            case "Airlangga" : airlanggaRb.setSelected(true);break;
            case "Gramedia" : gramediaRb.setSelected(true);break;
            default:ygLainRb.setSelected(true);break;
        }
        tahunTerbitCb.setSelectedItem(String.valueOf(buku.getTahunTerbit()));
    }
    
    public void setBuku(Buku buku){
        this.buku=buku;
        showOldDataof(buku);
    }
    
    private String getSelectedPenerbit(){
        if(yudhistiraRb.isSelected()){
            return "Yudhistira";
        } else if(gramediaRb.isSelected()){
            return "Gramedia";
        } else if(airlanggaRb.isSelected()){
            return "Airlangga";
        } else if(ygLainRb.isSelected()){
            return "Yang Lain";
        } else{
            return "";
        }
    }
    
    private boolean validateAllInput(){
        String judul = judulField.getText();
        if (judul.isEmpty()) {
            showError("Judul buku masih kosong");
            return false;
        }
        String pengarang = pengarangField.getText();
        if (pengarang.isEmpty()) {
            showError("Pengarang buku masih kosong");
            return false;
        }
        String penerbit = getSelectedPenerbit();
        if (penerbit.isEmpty()) {
            showError("Penerbit belum ada yang dipilih");
            return false;
        }
        String tahunTerbit = tahunTerbitCb.getSelectedItem().toString();
        if (tahunTerbit.isEmpty()) {
            showError("Tahun terbit belum ada yang dipilih");
            return false;
        }

        return true;
    }
    
    private void collectDataFor(Buku buku) {
        String judul = judulField.getText();
        String pengarang = pengarangField.getText();
        String penerbit = getSelectedPenerbit();
        String tahunTerbit = tahunTerbitCb.getSelectedItem().toString();

        buku.setJudulBuku(judul);
        buku.setPengarang(pengarang);
        buku.setPenerbit(penerbit);
        buku.setTahunTerbit(Integer.parseInt(tahunTerbit));
    }

    private void saveNewData() {
        buku = new Buku();
        collectDataFor(buku);

        BukuDataSource datasource = new BukuDataSource();
        try {
            datasource.save(buku);
            showSucceed("Data buku berhasil disimpan");
            dispose();
        } catch (SQLException e) {
            showError("Data buku gagal disimpan");
            e.printStackTrace();
        }
    }

    private void updateData() {
        collectDataFor(buku);

        BukuDataSource datasource = new BukuDataSource();
        try {
            datasource.update(buku);
            showSucceed("Data buku berhasil diperbaharui");
            dispose();
        } catch (SQLException e) {
            showError("Data buku gagal diperbaharui");
            e.printStackTrace();
        }
    }

    private void simpan() {
        if (!validateAllInput()) {
            return;
        }

        if (buku != null) {
            updateData();
        } else {
            saveNewData();
        }
    }

    @Override
    public void setTitle(String title) {
        super.setTitle(title); //To change body of generated methods, choose Tools | Templates.
        titleActivity.setText(title);
    }
    /**
     * Creates new form FormBukuActivity
     */
    public FormBukuActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penerbitBtnG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleActivity = new javax.swing.JLabel();
        pengarangTitle = new javax.swing.JLabel();
        judulTitle = new javax.swing.JLabel();
        penerbitTitle = new javax.swing.JLabel();
        pengarangField = new javax.swing.JTextField();
        judulField = new javax.swing.JTextField();
        yudhistiraRb = new javax.swing.JRadioButton();
        airlanggaRb = new javax.swing.JRadioButton();
        gramediaRb = new javax.swing.JRadioButton();
        ygLainRb = new javax.swing.JRadioButton();
        tahunTerbitCb = new javax.swing.JComboBox<>();
        tanggalTerbitTitle = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleActivity.setText("Form Buku");

        pengarangTitle.setText("Pengarang");

        judulTitle.setText("Judul");

        penerbitTitle.setText("Penerbit");

        pengarangField.setToolTipText("");

        judulField.setToolTipText("");

        penerbitBtnG.add(yudhistiraRb);
        yudhistiraRb.setText("Yudhistira");
        yudhistiraRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yudhistiraRbActionPerformed(evt);
            }
        });

        penerbitBtnG.add(airlanggaRb);
        airlanggaRb.setText("Airlangga");
        airlanggaRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlanggaRbActionPerformed(evt);
            }
        });

        penerbitBtnG.add(gramediaRb);
        gramediaRb.setText("Gramedia");
        gramediaRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gramediaRbActionPerformed(evt);
            }
        });

        penerbitBtnG.add(ygLainRb);
        ygLainRb.setText("Yang lain");
        ygLainRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ygLainRbActionPerformed(evt);
            }
        });

        tahunTerbitCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        tanggalTerbitTitle.setText("Tanggal Terbit");

        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleActivity)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pengarangTitle)
                            .addComponent(judulTitle)
                            .addComponent(penerbitTitle)
                            .addComponent(tanggalTerbitTitle))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pengarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(airlanggaRb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ygLainRb))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(yudhistiraRb)
                                    .addGap(18, 18, 18)
                                    .addComponent(gramediaRb)))
                            .addComponent(tahunTerbitCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addGap(18, 18, 18)
                .addComponent(saveBtn)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleActivity))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judulTitle))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pengarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pengarangTitle))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(penerbitTitle)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yudhistiraRb)
                        .addComponent(gramediaRb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlanggaRb)
                    .addComponent(ygLainRb))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahunTerbitCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalTerbitTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yudhistiraRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yudhistiraRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yudhistiraRbActionPerformed

    private void airlanggaRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlanggaRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlanggaRbActionPerformed

    private void gramediaRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gramediaRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gramediaRbActionPerformed

    private void ygLainRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ygLainRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ygLainRbActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBukuActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton airlanggaRb;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton gramediaRb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField judulField;
    private javax.swing.JLabel judulTitle;
    private javax.swing.ButtonGroup penerbitBtnG;
    private javax.swing.JLabel penerbitTitle;
    private javax.swing.JTextField pengarangField;
    private javax.swing.JLabel pengarangTitle;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> tahunTerbitCb;
    private javax.swing.JLabel tanggalTerbitTitle;
    private javax.swing.JLabel titleActivity;
    private javax.swing.JRadioButton ygLainRb;
    private javax.swing.JRadioButton yudhistiraRb;
    // End of variables declaration//GEN-END:variables
}
